name: First GitHub Actions Workflow

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  say-welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Welcome to GitHub Actions!"
